### ISSUE TITLE
Possible different firmware version gives different command?

### ISSUE THREAD

**Issue by HappyZ** [badicsalex/ar-drivers-rs#14]
In your blog post, it states CommandID of brightness level for XREAL Light is 'Y' (0x59) but upon testing in firmware 05.5.08.059_20230518, I see 0x31 is actually the brightness level.

I haven't tested others, but might be good to have a firmware check?

**Comment by HappyZ** [comment]
also your blog post https://voidcomputing.hu/blog/good-bad-ugly/ has a typo for Light:

Enable ambient light reporting | 1 | L | "0": Disable"1": Enable
-- | -- | -- | --
Enable v-sync reporting | 1 | L | "0": Disable"1": Enable

both says L, should be N for vsync

**Comment by badicsalex** [comment]
Apparently 0x59 is "Set Bright Level" (according to the logs in the FW), while 0x31 is "Set Light level". I have no idea what the difference is, never dug down deep enough.

I faintly remember actually testing it, but I'm not sure. If you did, and it seems that 0x31 is the right command, I'll fix the post.

**Comment by HappyZ** [comment]
yep I tested 0x31 and it worked out. 

2024/06/02 04:48:53.323213 INFO 'get' : '0x56 (V)' : ' ' : unknown : 'NrealFW'
2024/06/02 04:48:53.325181 INFO 'get' : '0x58 (X)' : ' ' : unknown : 'STM32F413MGY6'
2024/06/02 04:48:53.327180 INFO 'get' : '0x59 (Y)' : ' ' : unknown : 'ROM_1.5Mbytes'
2024/06/02 04:48:53.329267 INFO 'get' : '0x5a (Z)' : ' ' : unknown : 'RAM_320Kbytes'
2024/06/02 04:48:53.334215 INFO 'get' : '0x60 (`)' : ' ' : unknown : '0'

0x59 is something odd

where do you see the logs from FW? I'm also trying to get an idea what each does

**Comment by badicsalex** [comment]
Haha, you're right!

CMD 1(set)/'Y' is Set brightness, but CMD 3(get)/'Y' is that CPU info thing. I'll fix the blogpost.

As far as I see, the command categories "1" and "3" are the "normal" commands, the "@" category is a bunch of system stuff, "F" is for development and factory tests, and "T" is for calibration. All of which have a whole lot of commands.

I'm using ghidra to look at the internals of the firmware. E-mail me or add me on discord (@stikmann), and I can tell you more, because I'm uncomfortable sharing more in public.

**Comment by HappyZ** [comment]
thanks. closing this thread as you've answered it.

**Comment by HappyZ** [comment]
fyi I tested, setting both '1' and 'Y' works, but you cannot get 'Y' for the level. Still digesting newer firmware to understand but my 5cents is 'Y' will be removed for something else.
