### ISSUE TITLE
XREAL Light PacketTimeout when setting display mode on latest firmware

### ISSUE THREAD

**Issue by luveti** [badicsalex/ar-drivers-rs#7]
I'm having trouble putting my Lights into Stereo mode.

They're running firmware version `05.5.08.059_20230518`, which appears to be the latest.

I added the following to NrealLight::new_common to print the firmware version:
```rs
let res = result.run_command(Packet {
    category: b'3',
    cmd_id: b'5',
    ..Default::default()
})?;
println!("firmware version={}", String::from_utf8(res).map_err(|_| Error::Other("Firmware version was not utf-8")).unwrap());
```

Could you check what firmware version you're running on your glasses?

The following firmwares are available in the latest APK:

`01.1.04.008_20200922.bin`
`02.1.04.008_20200922.bin`
`03.1.04.008_20200922.bin`
`05.1.08.003_20220523.bin`
`05.5.08.056_20230317.bin`
`05.5.08.059_20230518.bin`

I intend to use the sources available here https://ota.xreal.com/en/light-activation.html to downgrade my glasses to whatever version you're using.

A Rust port should be easy enough and could be included in this repo if you'd like.

**Comment by badicsalex** [comment]
Hi,

I'm using 05.1.08.021_20221114.bin, but instead of you downgrading, the timeout bug should be fixed instead IMO. Have you tried increasing the command timeout? That might be enough. If that's not enough, maybe we should use some alternative display mode switching command.

A firmware update functionality would be pretty great actually, so I'd really appreciate that.

By the way, if you screw up the firmware update, there's an emergency boot mode on the glasses if you long press one of the buttons while powering it up. It then comes up as a serial console so you can unbrick it. This blogpost may or may not be related: https://voidcomputing.hu/blog/crc-reversing/ :)

**Comment by luveti** [comment]
I did try increasing the timeout to no avail. It's possible there's a new command that needs used but my reverse engineering skills are zero!

I've managed to get a firmware flasher put together based on the sources on that site. It works great! Here it is: https://github.com/luveti/xreal-light-firmware-flasher

I did actually fail to flash an image part way through (wasn't reading from the serial port, so it would hang). It appears the glasses just boot into flashing mode when an update fails. Which is awesome to see! This may not always be the case, so it's great to know you can force it with the button press.

But... the firmware update didn't help. It looks like the reason has nothing to with the firmware, but is instead due to a [this change](https://github.com/badicsalex/ar-drivers-rs/commit/973f0cffcd968f9f9d90997700d06b35fa071479#diff-c535de926e1e8c28e87bf12a857584895578569e2226b0eed4b2ef6309e87ba8).

The MCU is expecting the display mode as ASCII numbers, but this commit changed it to use decimals numbers.

Reverting that change fixes the issue! It works on both your firmware and the latest firmware. So no changes are required on that end.

**Comment by badicsalex** [comment]
Damn, that's some big regression right there! I need to test changes more, but it gets difficult with this many glasses :)

But at least now I know about your firmware flasher project, it will be quite handy.
